 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: nuget restore VirtualWork.sln
       - run: msbuild VirtualWork.sln
       - run: VSTest.Console.exe "VirtualWork.Tests\bin\Debug\VirtualWork.Tests.dll"
