 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: nuget restore VirtualWork.sln
       - run: msbuild VirtualWork.sln
       
- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\*test*.dll
     **\$(BuildConfiguration)\**\*test*.dll
     !**\*Microsoft.VisualStudio.TestPlatform*
     !**\obj\**

    vstestLocationMethod: location
    vstestLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow'
    codeCoverageEnabled: true
    otherConsoleOptions: '/platform:x64 /Framework:FrameworkCore10 /logger:console;verbosity="normal" '
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'