// <auto-generated />
namespace VirtualWork.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IntroduceAppointmentEndDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntroduceAppointmentEndDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202009262144280_IntroduceAppointmentEndDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
